[server]
maxUploadSize = 12
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#7c3aed"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#111111"
